"""
Simple script that inspects SQLAlchemy models and writes pydantic skeletons into app/schemas/autogen_schemas.py
"""
from sqlalchemy.inspection import inspect
from app.models import models as MODEL_MODULE
import inspect as pyinspect

OUTPATH = 'app/schemas/autogen_schemas.py'
lines = [
    "# Autogenerated Pydantic models — review & edit before production\n",
    "from pydantic import BaseModel\n",
    "from typing import Optional\n\n",
]
for name, obj in pyinspect.getmembers(MODEL_MODULE, pyinspect.isclass):
    if getattr(obj, '__tablename__', None):
        lines.append(f"class {name}Base(BaseModel):\n")
        mapper = inspect(obj)
        for col in mapper.columns:
            colname = col.key
            lines.append(f"    {colname}: Optional[str] = None\n")
        lines.append('\n')
with open(OUTPATH, 'w') as f:
    f.writelines(lines)
print('Wrote', OUTPATH)
